-- Create the claimed_numbers table
create table claimed_numbers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  number integer not null check (number >= 1 and number <= 6),
  client_id text not null,
  constraint unique_number unique (number),
  constraint unique_client unique (client_id)
);

-- Enable RLS
alter table claimed_numbers enable row level security;

-- Create policies
create policy "Anyone can insert claims"
  on claimed_numbers for insert
  with check (true);

create policy "Anyone can view claims"
  on claimed_numbers for select
  using (true);

-- Create index for faster lookups
create index idx_client_id on claimed_numbers(client_id);
create index idx_number on claimed_numbers(number);